apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.bitwarden }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end}}
  database_url: {{ include "vaultwarden.dbUrl" . }}
