apiVersion: v1
kind: Secret
metadata:
  name: admin-token
  namespace: {{ include "vaultwarden.fullname" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
  # labels TODO
type: Opaque
data:
  admin-token: {{ include "vaultwarden.adminToken" . }}
