{{- if .Values.azure-pg.postgres.server.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure-pg.postgres.server.secret.name }}
type: Opaque
stringData:
  {{- $pwd := (lookup "v1" "Secret" .Release.Namespace "jwt-pwd") | default dict }}
  {{- $pwdData := (get $pwd "data") | default dict }}
  {{- $pwdSecret := (get $pwdData "PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.azure-pg.postgres.server.secret.key }}: {{ $pwdSecret | b64enc | quote }}
{{- end }}
