apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}-config
  labels:
    {{- include "identity.labels" . | nindent 4 }}
data:
  config.yaml: |-
    app:
      key: {{ .Values.configs.app.key }}
      baseurl: {{ .Values.configs.app.baseurl }}
      redirectUri: {{ .Values.configs.app.redirectUri }}
      {{- with .Values.configs.app.allowance }}
      allowance: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
    courier:
      sender: {{ .Values.configs.courier.sender }}
      nats:
        url: {{ include "nats.url" . }}
      driver:
        type: {{ .Values.configs.courier.driver.type }}
        config:
          key: {{ .Values.configs.courier.driver.config.key }}
          secret: {{ .Values.configs.courier.driver.config.secret }}
          region: {{ .Values.configs.courier.driver.config.region }}
    sentry:
      url: {{ .Values.configs.sentry.url }}
      environment: {{ .Values.configs.sentry.environment }}
    server:
      api:
        addr: {{ .Values.configs.server.api.addr }}
        timeout: {{ .Values.configs.server.api.timeout }}
      ui: 
        addr: {{ .Values.configs.server.ui.addr }}
        timeout: {{ .Values.configs.server.ui.timeout }}
      grpc:
        addr: {{ .Values.configs.server.grpc.addr }}
        timeout: {{ .Values.configs.server.grpc.timeout }}
    repository:
      type: {{ .Values.configs.repository.type }}
      config:
        database: {{ .Values.azure.postgres.database.name }}
        user: {{ .Values.azure.postgres.server.username }}
        password: "TODO"
        host: {{ include "postgres.url" . }}
        port: {{ .Values.azure.postgres.server.port }}
    session:
      cookieDomain: {{ .Values.configs.session.cookieDomain | quote }}
      cookieName: {{ .Values.configs.session.cookieName }}
      driver: {{ .Values.configs.session.driver }}
      config: 
        host: {{ include "redis.url" . }}
        password: {{ .Values.configs.session.config.password }}
        port: {{ .Values.configs.session.config.port }}
        database: {{ .Values.configs.session.config.database }}
    {{- with .Values.configs.connectors }}
    connectors:
      {{- toYaml . | nindent 6 }}
    {{- end }}