apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}-config
  labels:
    {{- include "identity.labels" . | nindent 4 }}
data:
  config.yaml: |-
    app:
      key: {{ .Values.configs.app.key }}
      url: {{ .Values.configs.app.url }}
      redirectUri: {{ .Values.configs.app.redirectUri }}
      {{- with .Values.configs.app.whitelisted_redirect_uris }}
      whitelisted_redirect_uris: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
    courier:
      sender: {{ .Values.configs.courier.sender }}
      nats:
        url: {{ .Values.configs.courier.nats.url }}
      driver:
        type: {{ .Values.configs.courier.driver.type }}
        config:
          key: {{ .Values.configs.courier.driver.config.key }}
          secret: {{ .Values.configs.courier.driver.config.secret }}
          region: {{ .Values.configs.courier.driver.config.region }}
    sentry:
      url: {{ .Values.configs.sentry.url }}
      environment: {{ .Values.configs.sentry.environment }}
    server:
      api:
        addr: {{ .Values.configs.server.api.addr }}
        timeout: {{ .Values.configs.server.api.timeout }}
      grpc:
        addr: {{ .Values.configs.server.grpc.addr }}
        timeout: {{ .Values.configs.server.grpc.timeout }}
    repository:
      type: {{ .Values.configs.repository.type }}
      config:
        file: {{ .Values.configs.repository.config.file }}
    session:
      cookieDomain: {{ .Values.configs.session.cookieDomain }}
      cookieName: {{ .Values.configs.session.cookieName }}
      driver: {{ .Values.configs.session.driver }}
      config: 
        host: {{ .Values.configs.session.config.host }}
        password: {{ .Values.configs.session.config.password }}
        port: {{ .Values.configs.session.config.port }}
        database: {{ .Values.configs.session.config.database }}
    {{- with .Values.configs.connectors }}
    connectors
      {{- toYaml . | nindent 6 }}
    {{- end }}