kubernetesNamespace: default
location: westeurope
resourceGroup:
  create: true
  name: knkcms
postgres:
  server:
    create: true
    name: knkcms-dev
    version: 13
    sku:
      name: Standard_B1ms
      tier: Burstable
    username: knkAdmin
    password: Password4knk
    port: 5432
    firewall:
      createAzureRule: true
  database:
    create: true
    name: knkcms-dev
