apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema.fullname" . }}-config
  labels:
    {{- include "schema.labels" . | nindent 4 }}
data:
  config.yaml: |-
    sentry:
      url: {{ .Values.configs.sentry.url }}
      environment: {{ .Values.configs.sentry.environment }}
    server:
      api:
        addr: {{ .Values.configs.server.api.addr }}
        timeout: {{ .Values.configs.server.api.timeout }}
      grpc:
        addr: {{ .Values.configs.server.grpc.addr }}
        timeout: {{ .Values.configs.server.grpc.timeout }}
    repository:
      type: "postgres"
      config:
        database: {{ .Values.azure.postgres.database.name }}
        user: {{ .Values.azure.postgres.server.username }}
        password: "TODO"
        host: {{ include "postgres.url" . }}
        port: {{ .Values.azure.postgres.server.port }}