apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema.fullname" . }}
  labels:
    {{- include "schema.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - port: {{ .Values.configs.server.api.port }}
      targetPort: {{ .Values.configs.server.api.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.configs.server.grpc.port }}
      targetPort: {{ .Values.configs.server.grpc.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "schema.selectorLabels" . | nindent 4 }}
