{{- if .Values.azure.redis.create }}
apiVersion: cache.azure.com/v1alpha1api20201201
kind: Redis
metadata:
  name: {{ .Values.azure.redis.name }}
  namespace: {{ .Values.azure.kubernetesNamespace }}
spec:
  location: {{ .Values.azure.location }}
  owner:
    name: {{ .Values.azure.resourceGroup.name }}
  sku:
    family: {{ .Values.azure.redis.sku.family }}
    name: {{ .Values.azure.redis.sku.name }}
    capacity: {{ .Values.azure.redis.sku.capacity }}
  enableNonSslPort: {{ .Values.azure.redis.enableNonSslPort }}
  minimumTlsVersion: {{ .Values.azure.redis.minimumTlsVersion | quote }}
  redisVersion: {{ .Values.azure.redis.version | quote }}
{{- end }}