apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cms-org.fullname" . }}-backend-config
  labels:
    {{- include "cms-org.labels" . | nindent 4 }}
data:
  config.yaml: |-
    server:
      http:
        addr: {{ .Values.backend.configs.server.http.addr }}
        timeout: {{ .Values.backend.configs.server.http.timeout }}
      grpc:
        addr: {{ .Values.backend.configs.server.grpc.addr }}
        timeout: {{ .Values.backend.configs.server.grpc.timeout }}
      dev_mode: {{ .Values.backend.configs.server.dev_mode }}
    data:
      database:
        driverName: {{ .Values.backend.configs.data.database.driverName }}
        host: {{ .Values.backend.configs.data.database.host }}
        name: {{ .Values.backend.configs.data.database.name }}
        user: {{ .Values.backend.configs.data.database.user }}
        password: {{ .Values.backend.configs.data.database.password }}
        sslmode: {{ .Values.backend.configs.data.database.sslmode }}
        max_open_connections: {{ .Values.backend.configs.data.database.max_open_connections }}
        max_idle_conns: {{ .Values.backend.configs.data.database.max_idle_conns }}
    features:
      default_list_page_size: {{ .Values.backend.configs.features.default_list_page_size }}
    domain:
      {{- with .Values.backend.configs.domain.system_domains }}
      system_domains:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      subdomain_transition_period: {{ .Values.backend.configs.domain.subdomain_transition_period }}