{{- if .Values.postgres.database.create }}
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersDatabase
metadata:
  name: {{ .Values.postgres.database.name }}
  namespace: {{ .Values.kubernetesNamespace }}
spec:
  owner:
    name: {{ .Values.postgres.server.name }}
  charset: utf8
{{- end }}