{{- if .Values.postgres.database.create }}
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: {{ .Values.postgres.database.name }}
spec:
  owner:
    name: {{ .Values.postgres.server.name }}
  charset: utf8
{{- end }}
