{{- if .Values.resourceGroup.create }}
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: {{ .Values.resourceGroup.name }}
  namespace: {{ .Values.kubernetesNamespace }}
spec:
  location: {{ .Values.location }}
{{- end }}