{{- if .Values.postgres.server.create }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-details
type: Opaque
stringData:
  USERNAME: {{ .Values.postgres.server.username }}
  SERVER:   "{{ .Values.postgres.database.name }}.postgres.database.azure.com"
  DATABASE: {{ .Values.postgres.database.name }}
  PORT:     {{ .Values.postgres.server.port | quote }}
{{- end }}
