{{- if .Values.postgres.server.create }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.kubernetesNamespace }}
type: Opaque
stringData:
  USERNAME: {{ .Values.postgres.server.username }}
  # {{- $pwd := (lookup "v1" "Secret" .Release.Namespace "jwt-pwd") | default dict }}
  # {{- $pwdData := (get $pwd "data") | default dict }}
  # {{- $pwdSecret := (get $pwdData "PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  # PASSWORD: {{ $pwdSecret | b64enc | quote }}
  PASSWORD: {{ .Values.postgres.server.password }}
  SERVER:   "{{ .Values.postgres.database.name }}.postgres.database.azure.com"
  DATABASE: {{ .Values.postgres.database.name }}
  PORT:     {{ .Values.postgres.server.port | quote }}
{{- end }}
