{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cms-core.fullname" . -}}
{{- $svcPort := .Values.service.port -}} # @TODO What to do here?
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cms-core.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # @ TODO Check if default backend is needed
  # defaultBackend:
  #   service:
  #     name: frontend-service
  #     port:
  #       number: 80
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    # OLD Generated
    # {{- range .Values.ingress.hosts }}
    # - host: {{ .host | quote }}
    #   http:
    #     paths:
    #       {{- range .paths }}
    #       - path: {{ .path }}
    #         backend:
    #           serviceName: {{ $fullName }}
    #           servicePort: {{ $svcPort }}
    #       {{- end }}
    # {{- end }}
  - host: {{ .host | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "cms-core.areaService" . }}
            port:
              number: {{ .Values.ingress.areaServicePort }} # 8080 # @TODO replace from values.yaml
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cms-core.frontendService" . }}
            port:
              number: {{ .Values.ingress.frontendServicePort }} # 80 # @TODO replace from values.yaml

  {{- end }}
