apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    pg-cluster: {{ .Values.postgres.name | quote }}
    vendor: crunchydata
  name: {{ .Values.postgres.name }}-{{- if .Values.postgres.username }}{{ .Values.postgres.username }}{{- else }}{{ .Values.postgres.name }}{{- end }}-secret
  namespace: {{ .Values.postgres.namespace | quote }}
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
  username: {{ if .Values.postgres.username }}{{ .Values.postgres.username | b64enc | quote }}{{- else }}{{ .Values.postgres.name | b64enc | quote }}{{- end }}