apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ .Values.postgres.name }}-cluster" # "acid-minimal-cluster" # {{ .Values.name }} Name need to start with the value of teamId https://github.com/zalando/postgres-operator/blob/master/docs/user.md
  namespace: {{ .Values.postgres.namespace }}
spec:
  teamId: {{ .Values.postgres.name }} # "acid" 
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    {{ .Values.postgres.username }}: # zalando:  # database owner
    - superuser
    - createdb
    {{ .Values.postgres.username }}_user: []  # role for application foo
  databases:
    {{ .Values.postgres.databasename }}: {{ .Values.postgres.username }} # zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "13"