apiVersion: v1
kind: Service
metadata:
  name: {{ include "cms-core.frontendService" . }}
  labels:
    {{- include "cms-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cms-core.selectorFrontendLabels" . | nindent 4 }}
