{{- if .Values.azure.postgres.server.create }}
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServer
metadata:
  name: {{ .Values.azure.postgres.server.name }}
  namespace: {{ .Values.azure.kubernetesNamespace }}
spec:
  location: {{ .Values.azure.location }}
  owner:
    name: {{ .Values.azure.resourceGroup.name }}
  version: {{ .Values.azure.postgres.server.version | quote }}
  sku:
    name: {{ .Values.azure.postgres.server.sku.name }}
    tier: {{ .Values.azure.postgres.server.sku.tier }}
  administratorLogin: {{ .Values.azure.postgres.server.credentials.user }}
  administratorLoginPassword: 
    name: TODO
    key: TODO
  storage:
    storageSizeGB: 128
{{- end }}