{{- if .Values.postgres.server.create }}
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServer
metadata:
  name: {{ .Values.postgres.server.name }}
  namespace: {{ .Values.postgres.server.namespace }}
spec:
  location: {{ .Values.postgres.server.location }}
  owner:
    name: {{ .Values.postgres.server.resourcegroup }}
  version: {{ .Values.postgres.server.version }}
  sku:
    name: {{ .Values.postgres.server.sku.name }}
    tier: {{ .Values.postgres.server.sku.tier }}
  administratorLogin: {{ .Values.postgres.server.credentials.user }}
  administratorLoginPassword: {{ .Values.postgres.server.credentials.password }}
  storage:
    storageSizeGB: 128
{{- end }}