apiVersion: v2
name: vaultwarden
description: A Helm chart for Kubernetes

icon: https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png

type: application

appVersion: "1.16.0"

dependencies:
  - name: azure-pg
    version: "0.1.4"
    repository: https://knkcms.github.io/charts
