{{- if .Values.frontend.ingress.enabled -}}
{{- $fullName := include "cms-solution.fullname" . -}}
{{- $svcPort := .Values.frontend.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: "ingress-frontend" # {{ $fullName }}
  labels:
    {{- include "cms-solution.labels" . | nindent 4 }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: cms-frontend.northeurope.az.preview.knkcms.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: area-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
{{- end }}
