apiVersion: v1
kind: Service
metadata:
  name: "frontend-service" # {{ include "cms-solution.fullname" . }}
  labels:
    {{- include "cms-solution.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: app
  selector: 
    app.kubernetes.io/name: cms-solution-frontend
    app.kubernetes.io/instance: knkcms
